# 根目录配置
asset_root: "/home/avent/assets/5.0 assets/"

# 1 Simulation config
simulation_app:
  config: {"headless": True, "realtime_factor": 1.0}
  stage_file_path: "/home/vn/Documents/IsaacSimAssets/Assets/Isaac/5.0/Isaac/VN(back_up)/Stages/ForkliftE_Container.usd"
  controller_class: "ForkliftE"
  actuators_config: "../configs/e/Actuators.config"
  sensors_config: "../configs/e/Sencers.config"
  physics_dt: 0.01
  rendering_dt: 0.05

# 2 车辆信息
vehicle:
    name : "ForkliftE"
    prim_path: "/World/E_car_finish"
    pose_prim_path: "/World/forklift_E/Links/body"
    vehicle_state_topic: "vehicle/status"  # 修改为status以便UI直接订阅
    ui_cmd_topic: "ui/cmd"       # UI控制指令主题
    keyboard_topic: "keyboard/cmd"
    adjust_ctrl_topic: "adjust_ctrl/cmd"
    agv_ctrl_topic: "agv/cmd"
    fork_joint_names: ["fork_z"]   # Fork height, side-shift, mast tilt
    door_joint_names: ["door_frame"]
    drive_wheel_joint_names: ["back_wheel"]
    steer_wheel_joint_names: ["steer_wheel"]
    drive_wheel_radius: 0.5

# 3 传感器配置
sensors:
  # 激光雷达(用于避障和建图)

  lidar_1:
    type: "mid_360"
    prim_path: "/World/mid360_front"
    topic_name: "192.168.102.109"
    params:
      npy_path: "../configs/mid360.npy"
      parent_xform_path: "/World/forklift_E/Links/body"
      sampling_hz: 200000
      min_range: 0.1
      max_range: 60
      batch_size: 20000
      draw_points: True
      draw_lines: False
      position: [-1.84,0,2.5]   #单位m
      rotation: [0, 90, 0]     #角度
      compensate_parent_scale: True

  lidar_2:
    type: "mid_360"
    prim_path: "/World/mid360_right"
    topic_name: "192.168.102.110"
    params:
      npy_path: "../configs/mid360.npy"
      parent_xform_path: "/World/forklift_E/Links/body"
      sampling_hz: 200000
      min_range: 0.1
      max_range: 60
      batch_size: 20000
      draw_points: True
      draw_lines: False
      position: [ -1.84,-0.7,2.5 ]   #单位m
      rotation: [ -90,0,0 ]
      compensate_parent_scale: True

  lidar_3:
    type: "mid_360"
    prim_path: "/World/mid360_left"
    topic_name: "192.168.102.111"
    params:
      npy_path: "../configs/mid360.npy"
      parent_xform_path: "/World/forklift_E/Links/body"
      sampling_hz: 200000
      min_range: 0.1
      max_range: 60
      batch_size: 20000
      draw_points: True
      draw_lines: False
      position: [ -1.84,0.7,2.5 ]   #单位cm
      rotation: [ 90,0,0 ]
      compensate_parent_scale: True

  lidar_4:
    type: "mid_360"
    prim_path: "/World/mid360_fork"
    topic_name: "192.168.102.112"
    params:
      npy_path: "../configs/mid360.npy"
      parent_xform_path: "/World/forklift_E/Links/fork"
      sampling_hz: 200000
      min_range: 0.1
      max_range: 60
      batch_size: 20000
      draw_points: True
      draw_lines: False
      position: [ 1,0,0.1 ]   #单位cm
      rotation: [ 0,0,180 ]
      compensate_parent_scale: True

  # 摄像头(用于视觉识别)
  #水平分辨率的计算公式:HFOV=2×arctan(horizontal_aperture/(2×focal_length))
  #垂直分辨率的计算公式:VFOV=2×arctan(vertical_aperture/(2×focal_length))
  #focal_length_x = pixel_size * fx * 1e-6  # fx是内参矩阵中的水平焦距（像素单位），转换为米
  #focal_length_y = pixel_size * fy * 1e-6  # fy是内参矩阵中的垂直焦距（像素单位），转换为米
  #focal_length = (focal_length_x + focal_length_y) / 2  # 最终设置的平均焦距

  fork_camera:
    type: "camera.rgb"
    prim_path: "/World/forklift_E/Links/fork/fork_camera"
    params:
      width: 1280
      height: 960
      fps: 20
      position: [90,0,140]                #方位
      orientation: [90,-90,0]                  #旋转XYZ
      camera_matrix: [[958.8, 0.0, 957.8], [0.0, 956.7, 589.5], [0.0, 0.0, 1.0]]                   #相机内参
      focus_distance: 3                #焦距
      f_stop:                           #光圈值
      pixel_size: 3                      #像素大小
      distortion_way: "fish"                    #畸变方法
      clipping_range: [ 0.05,100000 ]      #设置裁剪范围
      distortion_coefficients: [0.14, -0.03, -0.0002, -0.00003, 0.009, 0.5, -0.07, 0.017]
      set_focal_length: True
      set_hfov: 20


  front_camera:
    type: "camera.rgb"
    prim_path: "/World/forklift_E/Links/body/body_front_camra"
    params:
      width: 1280
      height: 960
      fps: 20
      position:  [ 200,1,1 ]                     #方位单位cm
      orientation:                    #旋转
      camera_matrix: [ [ 958.8, 0.0, 957.8 ], [ 0.0, 956.7, 589.5 ], [ 0.0, 0.0, 1.0 ] ]                    #相机内参
      focus_distance: 1.5                   #焦距
      f_stop: 1.8                           #光圈值
      pixel_size: 3                      #像素大小
      distortion_way: "fish"                    #畸变方法
      clipping_range: [ 0.05,100000 ]      #设置裁剪范围
      distortion_coefficients: [ 0.05, 0.01, -0.003, -0.0005 ]
      set_focal_length: True
      set_hfov: 20

  back_camera:
    type: "camera.rgb"
    prim_path: "/World/forklift_E/Links/body/body_back_camra"
    params:
      width: 1280
      height: 960
      fps: 20
      position: [ 1,1,1 ]                   #方位
      orientation: [ 0,0,0 ]                     #旋转
      camera_matrix: [ [ 958.8, 0.0, 957.8 ], [ 0.0, 956.7, 589.5 ], [ 0.0, 0.0, 1.0 ] ]                    #相机内参
      focus_distance: 1.5                   #焦距
      f_stop: 1.8                           #光圈值
      pixel_size: 3                      #像素大小
      distortion_way: "fish"                    #畸变方法
      clipping_range: [ 0.05,100000 ]      #设置裁剪范围
      distortion_coefficients: [ 0.05, 0.01, -0.003, -0.0005 ]
      set_focal_length: True
      set_hfov: 20