# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: imu.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import Quaternion_pb2 as Quaternion__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\timu.proto\x12\x03imu\x1a\x10Quaternion.proto\"\x90\x02\n\x03Imu\x12\x0b\n\x03seq\x18\x01 \x01(\r\x12\x11\n\ttimestamp\x18\x02 \x01(\x04\x12\x1d\n\x15linear_acceleration_x\x18\x03 \x01(\x02\x12\x1d\n\x15linear_acceleration_y\x18\x04 \x01(\x02\x12\x1d\n\x15linear_acceleration_z\x18\x05 \x01(\x02\x12\x1b\n\x13\x61nguldar_velocity_x\x18\x06 \x01(\x02\x12\x1b\n\x13\x61nguldar_velocity_y\x18\x07 \x01(\x02\x12\x1b\n\x13\x61nguldar_velocity_z\x18\x08 \x01(\x02\x12)\n\x0borientation\x18\t \x01(\x0b\x32\x14.foxglove.Quaternion\x12\n\n\x02ip\x18\n \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'imu_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _IMU._serialized_start=37
  _IMU._serialized_end=309
# @@protoc_insertion_point(module_scope)
