# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: imudata.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from foxglove import Point3_pb2 as foxglove_dot_Point3__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rimudata.proto\x12\x02pb\x1a\x15\x66oxglove/Point3.proto\"\x84\x01\n\x07ImuData\x12%\n\x0borientation\x18\x01 \x01(\x0b\x32\x10.foxglove.Point3\x12*\n\x10\x61ngular_velocity\x18\x02 \x01(\x0b\x32\x10.foxglove.Point3\x12&\n\x0c\x61\x63\x63\x65leration\x18\x03 \x01(\x0b\x32\x10.foxglove.Point3b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'imudata_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _IMUDATA._serialized_start=45
  _IMUDATA._serialized_end=177
# @@protoc_insertion_point(module_scope)
