# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: point_cloud.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11point_cloud.proto\x12\x02pb\"\x88\x01\n\x0bPointCloud2\x12\x0b\n\x03seq\x18\x01 \x01(\r\x12\x11\n\ttimestamp\x18\x02 \x01(\x04\x12\x10\n\x08\x66rame_id\x18\x03 \x01(\t\x12\x0c\n\x04size\x18\x04 \x01(\r\x12\x11\n\tsend_time\x18\x05 \x01(\x04\x12\x14\n\x0c\x63onvert_time\x18\x06 \x01(\x02\x12\x10\n\x04\x64\x61ta\x18\x07 \x03(\x02\x42\x02\x10\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'point_cloud_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _POINTCLOUD2.fields_by_name['data']._options = None
  _POINTCLOUD2.fields_by_name['data']._serialized_options = b'\020\001'
  _POINTCLOUD2._serialized_start=26
  _POINTCLOUD2._serialized_end=162
# @@protoc_insertion_point(module_scope)
