# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Testing_msg.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import Quaternion_pb2 as Quaternion__pb2
from . import Vector3_pb2 as Vector3__pb2
from . import pose_pb2 as pose__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11Testing_msg.proto\x12\rsim_data_flow\x1a\x10Quaternion.proto\x1a\rVector3.proto\x1a\npose.proto\"k\n\x0bTesting_msg\x12\x0c\n\x04name\x18\x01 \x01(\t\x12&\n\x0btranslation\x18\x02 \x01(\x0b\x32\x11.foxglove.Vector3\x12&\n\x08rotation\x18\x03 \x01(\x0b\x32\x14.foxglove.Quaternion\"w\n\x0cMTesting_msg\x12\'\n\nrobot_pose\x18\x01 \x01(\x0b\x32\x13.sim_data_flow.Pose\x12+\n\x07msg_map\x18\x02 \x03(\x0b\x32\x1a.sim_data_flow.Testing_msg\x12\x11\n\ttimestamp\x18\x03 \x01(\x04\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Testing_msg_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TESTING_MSG._serialized_start=81
  _TESTING_MSG._serialized_end=188
  _MTESTING_MSG._serialized_start=190
  _MTESTING_MSG._serialized_end=309
# @@protoc_insertion_point(module_scope)
