# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vehicle_state_msg.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import Quaternion_pb2 as Quaternion__pb2
from . import Vector3_pb2 as Vector3__pb2
from . import pose_pb2 as pose__pb2
from . import imu_pb2 as imu__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17vehicle_state_msg.proto\x12\rsim_data_flow\x1a\x10Quaternion.proto\x1a\rVector3.proto\x1a\npose.proto\x1a\timu.proto\"\xa1\x04\n\x0fVehicleStateMsg\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x12\x16\n\x0e\x64rive_velocity\x18\x02 \x01(\x01\x12\x13\n\x0bsteer_angle\x18\x03 \x01(\x01\x12\x0f\n\x07wheel_l\x18\x04 \x01(\x01\x12\x0f\n\x07wheel_r\x18\x05 \x01(\x01\x12\x0e\n\x06\x66ork_x\x18\x06 \x01(\x01\x12\x0e\n\x06\x66ork_y\x18\x07 \x01(\x01\x12\x0e\n\x06\x66ork_z\x18\x08 \x01(\x01\x12\x0f\n\x07\x66ork_cl\x18\t \x01(\x01\x12\x0f\n\x07\x66ork_cr\x18\n \x01(\x01\x12\x11\n\tfork_roll\x18\x0b \x01(\x01\x12\x12\n\nfork_pitch\x18\x0c \x01(\x01\x12\x16\n\x0e\x61\x64just_control\x18\r \x01(\x08\x12\'\n\nrobot_pose\x18\x0e \x01(\x0b\x32\x13.sim_data_flow.Pose\x12(\n\x0btarget_pose\x18\x0f \x01(\x0b\x32\x13.sim_data_flow.Pose\x12\x13\n\x0b\x64\x61ta_record\x18\x10 \x01(\x08\x12\x15\n\x03imu\x18\x11 \x01(\x0b\x32\x08.imu.Imu\x12\x16\n\x0e\x64\x61taidx_upload\x18\x12 \x01(\r\x12\x15\n\rClampPressure\x18\x13 \x01(\x01\x12\x10\n\x08HSwitchL\x18\x14 \x01(\x08\x12\x10\n\x08HSwitchR\x18\x15 \x01(\x08\x12\x10\n\x08VSwitchL\x18\x16 \x01(\x08\x12\x10\n\x08VSwitchR\x18\x17 \x01(\x08\x12\x14\n\x0ctorquestatus\x18\x18 \x01(\x08\x12\x0f\n\x07seq_num\x18\x19 \x01(\x04\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vehicle_state_msg_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VEHICLESTATEMSG._serialized_start=99
  _VEHICLESTATEMSG._serialized_end=644
# @@protoc_insertion_point(module_scope)
