# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: VehicleControl.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14VehicleControl.proto\x12\tnmpc_test\")\n\x04Pose\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\x0b\n\x03yaw\x18\x03 \x01(\x01\"~\n\x05State\x12\x16\n\x0e\x64rive_velocity\x18\x01 \x01(\x01\x12\x11\n\tdrive_acc\x18\x02 \x01(\x01\x12\x13\n\x0bsteer_angle\x18\x03 \x01(\x01\x12\x16\n\x0esteer_velocity\x18\x04 \x01(\x01\x12\x1d\n\x04pose\x18\x05 \x01(\x0b\x32\x0f.nmpc_test.Pose\"&\n\x04Path\x12\x1e\n\x05poses\x18\x01 \x03(\x0b\x32\x0f.nmpc_test.Poseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'VehicleControl_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _POSE._serialized_start=35
  _POSE._serialized_end=76
  _STATE._serialized_start=78
  _STATE._serialized_end=204
  _PATH._serialized_start=206
  _PATH._serialized_end=244
# @@protoc_insertion_point(module_scope)
