# 1 Simulation config
simulation_app:
    config: {"headless": False}
    stage_file_path: "/home/vn/Documents/IsaacStages/Collected_WarehouseForkliftE/ForkliftE_test.usd"
    controller_class: "ForkliftE"

# 2 车辆信息
vehicle:
    name : "ForkliftE"
    prim_path: "/World/forklift_E"
    cmd_topic: "ackermann_control_cmd"
    fork_joint_names: ["fork_z", "fork_y", "fork_pitch"]   # Fork height, side-shift, mast tilt
    drive_wheel_joint_names: ["front_left_wheel", "front_right_wheel"]
    steer_wheel_joint_names: ["left_rotator", "right_rotator"]

# 3 传感器配置
sensors:
    # 激光雷达(用于避障和建图)
    lidar_0:
        type: "rtx_lidar"
        prim_path: ""
        params:

    lidar_1:
        type: "mid_360"
        prim_path: ""
        params:

    # 摄像头(用于视觉识别)
    #水平分辨率的计算公式:HFOV=2×arctan(horizontal_aperture/(2×focal_length))
    #垂直分辨率的计算公式:VFOV=2×arctan(vertical_aperture/(2×focal_length))
    #focal_length_x = pixel_size * fx * 1e-6  # fx是内参矩阵中的水平焦距（像素单位），转换为米
    #focal_length_y = pixel_size * fy * 1e-6  # fy是内参矩阵中的垂直焦距（像素单位），转换为米
    #focal_length = (focal_length_x + focal_length_y) / 2  # 最终设置的平均焦距

    fork_camera:
        type: "camera.rgb"
        prim_path: "/World/forklift_E/Links/lift/fork_cmara"
        params:
        width: 640
        height: 480
        fps: 20
        position:                          #方位
        orientation:                       #旋转
        horizontal_aperture:               #垂直光圈
        vertical_aperture:                 #水平光圈
        camera_matrix:                     #相机内参
        focus_distance:                    #焦距
        f_stop:                            #光圈值
        pixel_size:                        #像素大小


    front_camera:
        type: "camera.rgb"
        prim_path: "/World/forklift_E/Links/body/body_camra_front"
        params:
        width: 640
        height: 480
        fps: 20
        position:                          #方位
        orientation:                       #旋转
        horizontal_aperture:               #垂直光圈
        vertical_aperture:                 #水平光圈
        camera_matrix:                     #相机内参
        focus_distance:                    #焦距
        f_stop:                            #光圈值
        pixel_size:                        #像素大小

    back_camera:
        type: "camera.rgb"
        prim_path: "/World/forklift_E/Links/body/body_camra_back"
        params:
        width: 640
        height: 480
        fps: 20
        position:                          #方位
        orientation:                       #旋转
        horizontal_aperture:               #垂直光圈
        vertical_aperture:                 #水平光圈
        camera_matrix:                     #相机内参
        focus_distance:                    #焦距
        f_stop:                            #光圈值
        pixel_size:                        #像素大小

#
#  # 4.3 IMU传感器(用于姿态估计)
#  imu:
#    type: "sensor.imu"
#    prim_path: ""
#    params:




