# Topic names
/**:
    ros__parameters:
        Sensor:
            SemanticCloud: "/sensors/semantic_cloud"
            ColoredCloud: "/sensors/colored_cloud"

        TargetTopic:
            BBox: "/system/target/bbox"
            Pose: "/system/target/pose"


/system/control:
    ros__parameters:
        NMPC:
            Horizon: 20
            Dt: 0.1

            InputLen: 2
            StateLen: 4
            OutputLen: 4

            MaxAcc: 3.0
            MaxSpeed: 1.2

            MaxSteerSpeed: 0.5
            MaxSteerAngle: 1.14

            WheelBase: 1.37
            WheelRadius: 0.11

            WeightQ: [360.0, 660.0, 370.0, 60.0]
            WeightF: [4000.0, 4000.0, 4000.0]
            WeightR: [0.01, 0.001]


        